version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"       # Root directory where workflows live
    schedule:
      interval: "weekly" # Check weekly for updates
    commit-message:
      prefix: "chore"
      include: scope
    open-pull-requests-limit: 5
    reviewers:
      - lferrarotti74
    # Optional ignore block for major versions
    ignore:
      - dependency-name: "actions/checkout"
        versions:
          - ">=4"
      - dependency-name: "softprops/action-gh-release"
        versions:
          - ">=2"
